install.packages("tidyverse")
install.packages("shiny")
install.packages("shinydashboard")
install.packages("rmarkdown")
install.packages("httr")
install.packages("reshape2")
install.packages("pracma")